size = [10, 10]

[fixtures.1]
kind = "cheap_led_par_light"
channel = 0
mode = "0"
pos = [0, 0]

[fixtures.2]
kind = "cheap_led_par_light"
channel = 0
mode = "0"
pos = [0, 5]

[fixtures.3]
kind = "cheap_led_par_light"
channel = 0
mode = "1"
pos = [7, 5]

[fixtures.4]
kind = "cheap_led_par_light"
channel = 0
mode = "0"
pos = [10, 10]
