size = [10, 10]

[fixtures.1]
kind = "elation_colour_chorus_24"
channel = 1
mode = "18"
pos = [0, 5]

[fixtures.2]
kind = "elation_colour_chorus_24"
channel = 18
mode = "18"
pos = [5, 5]

[fixtures.3]
kind = "elation_colour_chorus_24"
channel = 35
mode = "18"
pos = [10, 5]

[fixtures.4]
kind = "elation_colour_chorus_24"
channel = 52
mode = "18"
pos = [15, 5]

[fixtures.5]
kind = "cheap_led_par_light"
channel = 69
mode = "0"
pos = [6, 2]

[fixtures.6]
kind = "cheap_led_par_light"
channel = 77
mode = "0"
pos = [8, 2]

[fixtures.7]
kind = "cheap_led_par_light"
channel = 85
mode = "0"
pos = [10, 2]


[fixtures.8]
kind = "cheap_led_par_light"
channel = 93
mode = "0"
pos = [12, 2]
