size = [10, 10]

[fixtures.1]
kind = "cheap_led_par_light"
channel = 1
mode = "0"
pos = [0, 0]

[fixtures.2]
kind = "cheap_led_par_light"
channel = 9
mode = "0"
pos = [0, 5]

[fixtures.3]
kind = "elation_colour_chorus_24"
channel = 17
mode = "18"
pos = [7, 5]
