installation="installation.toml"

[[scenes]]
name = "A"

  [[scenes.elements]]
  target = "5:1"
  color = 0x4300ff

[[scenes]]
name = "B"

  [[scenes.elements]]
  target = "5:1"
  color = 0xffffff

[[scenes]]
name = "Constant Pattern"

  [[scenes.patterns]]
  target = "g1"
  script = "constant.lua"
  color = 0x5050F0

[[scenes]]
name = "Pulse Pattern"

  [[scenes.patterns]]
  target = "g1"
  script = "pulse.lua"
  color = 0x50F040

[[scenes]]
name = "Rev. Pulse Pattern"

  [[scenes.patterns]]
  target = "g1"
  script = "pulse.lua"
  color = 0xC0C0FF
  reverse = true

  [[scenes.patterns]]
  target = "g2"
  script = "random_strobe.lua"

[[scenes]]
name = "White Light Pulse"

  [[scenes.patterns]]
  target = "g3"
  script = "pulse.lua"

[groups.1]
elements = ["1:1", "1:2", "1:3", "1:4", "2:1", "2:2", "2:3", "2:4",
            "3:1", "3:2", "3:3", "3:4", "4:1", "4:2", "4:3", "4:4"]

[groups.2]
elements = ["5:1", "6:1", "7:1", "8:1"]

[groups.3]
elements = ["9:1", "10:1", "11:1", "12:1", "13:1", "14:1", "15:1", "16:1", "17:1"]
