[[scenes]]
name = "A"
fixtures.1.elements.1 = 0x4300ff

[[scenes]]
name = "B"
fixtures.2.elements.1 = 0xffffff

[[scenes]]
name = "C"
fixtures.1.elements.1 = 0xff3000

[[scenes]]
name = "Simple Pattern"
groups.1.pattern = {script = "constant.lua", color = 0x5050F0}

[groups.1]
elements = ["1:1", "3:1", "3:2", "3:3", "3:4"]
