installation="installation.toml"

[[effects]]
name = "A"

  [[effects.elements]]
  target = "5:1:color"
  color = 0x4300ff

[[effects]]
name = "B"

  [[effects.elements]]
  target = "5:1:color"
  color = 0xffffff

[[effects]]
name = "Constant Pattern"

  [[effects.patterns]]
  target = "g1:color"
  script = "constant.lua"
  color = 0x5050F0

[[effects]]
name = "Pulse Pattern"

  [[effects.patterns]]
  target = "g1:color"
  script = "waveform.lua"
  color = 0x50F040

[[effects]]
name = "Rev. Pulse Pattern"

  [[effects.patterns]]
  target = "g1:color"
  script = "waveform.lua"
  color = 0xC0C0FF
  reverse = true

  [[effects.patterns]]
  target = "g2:color"
  script = "random_strobe.lua"

[[effects]]
name = "White Light Pulse"

  [[effects.patterns]]
  target = "g3:dimmer"
  script = "waveform.lua"
  reflect = 1

[pool]
A1 = "A"
A2 = "B"
B1 = "Constant Pattern"
B2 = "Pulse Pattern"
B3 = "Rev. Pulse Pattern"
B4 = "White Light Pulse"

[groups.1]
elements = ["1:1", "1:2", "1:3", "1:4", "2:1", "2:2", "2:3", "2:4",
            "3:1", "3:2", "3:3", "3:4", "4:1", "4:2", "4:3", "4:4"]

[groups.2]
elements = ["5:1", "6:1", "7:1", "8:1"]

[groups.3]
elements = ["9:1", "10:1", "11:1", "12:1", "13:1", "14:1", "15:1", "16:1", "17:1"]

[[cues]]
command = "a1 a2"
[[cues]]
command = "b1 b2"
[[cues]]
command = "b4"
